/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicTasksSyncRouteImport } from './routes/api/public/tasks/sync'
import { Route as ApiPublicObsidianOpenRouteImport } from './routes/api/public/obsidian/open'
import { Route as ApiPublicCronNotifyRouteImport } from './routes/api/public/cron/notify'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTasksSyncRoute = ApiPublicTasksSyncRouteImport.update({
  id: '/api/public/tasks/sync',
  path: '/api/public/tasks/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicObsidianOpenRoute = ApiPublicObsidianOpenRouteImport.update({
  id: '/api/public/obsidian/open',
  path: '/api/public/obsidian/open',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronNotifyRoute = ApiPublicCronNotifyRouteImport.update({
  id: '/api/public/cron/notify',
  path: '/api/public/cron/notify',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/cron/notify': typeof ApiPublicCronNotifyRoute
  '/api/public/obsidian/open': typeof ApiPublicObsidianOpenRoute
  '/api/public/tasks/sync': typeof ApiPublicTasksSyncRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/cron/notify': typeof ApiPublicCronNotifyRoute
  '/api/public/obsidian/open': typeof ApiPublicObsidianOpenRoute
  '/api/public/tasks/sync': typeof ApiPublicTasksSyncRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/cron/notify': typeof ApiPublicCronNotifyRoute
  '/api/public/obsidian/open': typeof ApiPublicObsidianOpenRoute
  '/api/public/tasks/sync': typeof ApiPublicTasksSyncRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/public/cron/notify'
    | '/api/public/obsidian/open'
    | '/api/public/tasks/sync'
    | '/api/public/telegram/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/public/cron/notify'
    | '/api/public/obsidian/open'
    | '/api/public/tasks/sync'
    | '/api/public/telegram/webhook'
  id:
    | '__root__'
    | '/'
    | '/api/public/cron/notify'
    | '/api/public/obsidian/open'
    | '/api/public/tasks/sync'
    | '/api/public/telegram/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicCronNotifyRoute: typeof ApiPublicCronNotifyRoute
  ApiPublicObsidianOpenRoute: typeof ApiPublicObsidianOpenRoute
  ApiPublicTasksSyncRoute: typeof ApiPublicTasksSyncRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tasks/sync': {
      id: '/api/public/tasks/sync'
      path: '/api/public/tasks/sync'
      fullPath: '/api/public/tasks/sync'
      preLoaderRoute: typeof ApiPublicTasksSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/obsidian/open': {
      id: '/api/public/obsidian/open'
      path: '/api/public/obsidian/open'
      fullPath: '/api/public/obsidian/open'
      preLoaderRoute: typeof ApiPublicObsidianOpenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/notify': {
      id: '/api/public/cron/notify'
      path: '/api/public/cron/notify'
      fullPath: '/api/public/cron/notify'
      preLoaderRoute: typeof ApiPublicCronNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicCronNotifyRoute: ApiPublicCronNotifyRoute,
  ApiPublicObsidianOpenRoute: ApiPublicObsidianOpenRoute,
  ApiPublicTasksSyncRoute: ApiPublicTasksSyncRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
