/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicTasksSyncRouteImport } from './routes/api/public/tasks/sync'
import { Route as ApiPublicCronNotifyRouteImport } from './routes/api/public/cron/notify'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTasksSyncRoute = ApiPublicTasksSyncRouteImport.update({
  id: '/api/public/tasks/sync',
  path: '/api/public/tasks/sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronNotifyRoute = ApiPublicCronNotifyRouteImport.update({
  id: '/api/public/cron/notify',
  path: '/api/public/cron/notify',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/public/cron/notify': typeof ApiPublicCronNotifyRoute
  '/api/public/tasks/sync': typeof ApiPublicTasksSyncRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/public/cron/notify': typeof ApiPublicCronNotifyRoute
  '/api/public/tasks/sync': typeof ApiPublicTasksSyncRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/public/cron/notify': typeof ApiPublicCronNotifyRoute
  '/api/public/tasks/sync': typeof ApiPublicTasksSyncRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/public/cron/notify' | '/api/public/tasks/sync'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/public/cron/notify' | '/api/public/tasks/sync'
  id: '__root__' | '/' | '/api/public/cron/notify' | '/api/public/tasks/sync'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiPublicCronNotifyRoute: typeof ApiPublicCronNotifyRoute
  ApiPublicTasksSyncRoute: typeof ApiPublicTasksSyncRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tasks/sync': {
      id: '/api/public/tasks/sync'
      path: '/api/public/tasks/sync'
      fullPath: '/api/public/tasks/sync'
      preLoaderRoute: typeof ApiPublicTasksSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/notify': {
      id: '/api/public/cron/notify'
      path: '/api/public/cron/notify'
      fullPath: '/api/public/cron/notify'
      preLoaderRoute: typeof ApiPublicCronNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiPublicCronNotifyRoute: ApiPublicCronNotifyRoute,
  ApiPublicTasksSyncRoute: ApiPublicTasksSyncRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
